[package]
name = "shader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { version = "0.9" }
bytemuck = { version = "1.17.0", features = ["derive"] }